import { Course, CourseType } from './course';

export const coursesMock: Course[] = [
  {
    id: '1',
    name: 'Analiza matematyczna 1',
    description: 'W ramach zajęć student powinien opanować podstawy rachunku różniczkowego i całkowego funkcji jednej zmiennej wraz z przykładowymi zastosowaniami.',
    ects: 6,
    type: CourseType.Lecture,
    semester: 1,
    attendee_limit: 100,
    image_url: 'https://www.trzcacak.rs/myfile/full/157-1577173_function-junction-and-the-limits-of-your-imagination.png',
    actual_note: 4.5,
    attendees: [],
  },
  {
    id: '2',
    name: 'Wstęp do informatyki',
    // tslint:disable-next-line:max-line-length
    description: 'Celem przedmiotu jest zapoznanie studentów z podstawowymi pojęciami informatyki, programowaniem w języku proceduralnym oraz wprowadzenie do podstawowych algorytmów i struktur danych.',
    ects: 6,
    type: CourseType.Lecture,
    semester: 1,
    attendee_limit: 100,
    image_url: 'https://b.thumbs.redditmedia.com/1Tj5A-SF1Wd0b5TOOKVm145yG88HEIbBwjIT6utaDDc.png',
    actual_note: 4,
    attendees: [],
  },
  {
    id: '3',
    name: 'Wprowadzenie do systemu UNIX',
    // tslint:disable-next-line:max-line-length
    description: 'Celem modułu jest wyposażenie studenta/studentki w umiejętność korzystania z systemu operacyjnego UNIX i na nim bazujących wykorzystując wiedzę o jego budowie i umiejętności praktyczne.',
    ects: 4,
    type: CourseType.Laboratory,
    semester: 1,
    attendee_limit: 80,
    image_url: 'https://cdn3.iconfinder.com/data/icons/logos-brands-3/24/logo_brand_brands_logos_linux-512.png',
    actual_note: 5,
    attendees: [],
  },
  {
    id: '4',
    name: 'Programowanie funkcyjne',
    // tslint:disable-next-line:max-line-length
    description: 'Kurs kładzie nacisk na zasady, techniki i wzorce programowania funkcyjnego, które są uniwersalne i przydatne w większości używanych obecnie języków programowania.',
    ects: 2,
    type: CourseType.Laboratory,
    semester: 3,
    attendee_limit: 24,
    image_url: 'https://miro.medium.com/max/800/1*7vAHJM0zD0ylgNFtSoPsnA.png',
    actual_note: 9,
    attendees: [],
  },
  {
    id: '5',
    name: 'Bazy danych',
    // tslint:disable-next-line:max-line-length
    description: 'Przedstawione zostaną metody dostępu do baz danych (zarówno relacyjnych jak i wybranych baz NoSQL) oraz przetwarzania danych przy wykorzystaniu różnych (wybranych) technologii i języków programowania.',
    ects: 2,
    type: CourseType.Lecture,
    semester: 4,
    attendee_limit: 150,
    image_url: 'https://cdn.iconscout.com/icon/free/png-512/database-449-133326.png',
    actual_note: 7,
    attendees: [],
  },
  {
    id: '6',
    name: 'Programowanie obiektowe',
    // tslint:disable-next-line:max-line-length
    description: 'Celem zajęć jest zaznajomienie studentów z paradygmatem programowania obiektowym. Studenci poznają techniki takie jak: dziedziczenie, delegowanie, ukrywanie implementacji.',
    ects: 4,
    type: CourseType.Project,
    semester: 3,
    attendee_limit: 24,
    image_url: 'https://d3q6qq2zt8nhwv.cloudfront.net/course/99cd34a1082d424c93463878b7d88a8a.png',
    actual_note: 10,
    attendees: [],
  },
  {
    id: '7',
    name: 'Fizyka',
    // tslint:disable-next-line:max-line-length
    description: 'Student jest zorientowany w zagadnieniach dotyczących fizyki współczesnej, na poziomie ogólnym. Rozumie znaczenie mechaniki kwantowej dla współczesnych rozwiązań technologicznych.',
    ects: 5,
    type: CourseType.Laboratory,
    semester: 3,
    attendee_limit: 16,
    image_url: 'https://icon-library.net/images/physics-icon/physics-icon-15.jpg',
    actual_note: 6,
    attendees: [],
  },
];
